name: 
description: Flutter plugin for triptracking — wraps native Android and iOS library.
version: 1.0.0
homepage: https://github.com/hieunguyentt/triptracking-library

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.carmd.triptracking.flutter
        pluginClass: triptrackingPlugin
      ios:
        pluginClass: triptrackingPlugin
